### ISSUE TITLE
Health Fehler

### ISSUE THREAD

**Issue by ibornlp** [ibornlp/Better-Commands-Plugin#4]
Den Healthfehler fixen

**Comment by ibornlp** [comment]
Eclipse zeigt da einen Fehler an

**Comment by FroznMine** [comment]
Der da lautet?

**Comment by ibornlp** [comment]
Eclipse meint ich soll wieder Health Schale nehmen... xD

**Comment by FroznMine** [comment]
Was hast du als Dependency?

**Comment by ibornlp** [comment]
Red mal Deutsch mit mir ich bin doch Doof und Unfähig

**Comment by ibornlp** [comment]
Den Fehler hab ich jetzt selber korrigiert !

XD

#Patchday02.03.
